
;<Program title>

jmp start

;data


;code
start: nop
LXI H,0000H
MOV A,M 
INX H
MOV B,M
LOOP: CMP B
JZ SKIP 	; IF A=B THEN JUMP TO THIS BLOCK
JC EXCHANGE 	;IF B>A JUMP TO THIS BLOCK
SUB B 		;A = A-B
JMP LOOP 	;UNCONDITIONAL JUMP
EXCHANGE: MOV C,B 
MOV B,A
MOV A,C
JMP LOOP 	;UNCONDITIONAL JUMP
SKIP: STA 000BH ;STORE ACCUMULATOR VALUE IN 000BH ADDRESS LOCATION
hlt